### PR TITLE
Upgrade all the things

### PR DESCRIPTION
**Pull request by riveramj**
Upgrades all around.

* Dispatch to 0.13.3
* sbt to 1.1.0
* scala to 2.12.4
* lift to 3.2.0

### CODE REVIEW

**Comment by riveramj** [comment]
@farmdawgnation Need a bit of help here. The `jvalue -> jfield` on 3.0 for lift is causing a bit of trouble and i'm not sure how to get around it. 

the issue at hand is 
```
def camelifyFieldNames(input: JValue): JValue = {
    input mapField {
      case JField(fieldName, value) =>
        JField(camelifyMethod(fieldName), value)
        
      case JArray(contents) =>
        JArray(contents.mapField(camelifyFieldNames))

      case obj @ JObject(fields) =>
        JObject(fields.mapField(camelifyFieldNames).asInstanceOf[List[JField]])

      case x =>
        x
    } 
  }
```

which namely is that `jarray` and `jobjects` and `jfield` are of diff types. 

I thought about breaking it out into two methods, but I dont think we'll know when its either a `jfield` or `array/object`.

Help?

**Comment by farmdawgnation** [comment]
Yeah, `JField` no longer extends `JValue`. This would probably be better implemented as a field transformer, which is a thing that I didn't know existed when I wrote this.

**Comment by riveramj** [comment]
@farmdawgnation got compilation and tests passing. give it a look.

**Comment by farmdawgnation** [comment]
Looks reasonable, let's see what CI says about my merge from master and go from there.

**Comment by riveramj** [comment]
All green here

**Pull request merged**
