### PR TITLE
Upcoming invoice improvements

### PR DESCRIPTION
**Pull request by farmdawgnation**
Supersedes #5.

cc @riveramj Try this on for size.

### CODE REVIEW

**Comment by riveramj** [comment]
Tried this out and its not returning the correct data. Currently if I run `Invoice.getUpcoming` and get the invoice returned, discount is `Full(None)`. If I curl the same, I get a full discount object. Same if I look at the upcoming invoice in the UI. Will look more at it later.

**Comment by riveramj** [comment]
The format of the `upcoming invoice` discount and an `existing invoice` discount is the same. If I call discount on `Invoice.get` I get everything fine in app.

Here is the curl output of `url https://api.stripe.com/v1/invoices/upcoming?customer=cus_9UTpVQq30U9bWb`
>{
  "object": "invoice",
  "amount_due": 1898,
  "application_fee": null,
  "attempt_count": 0,
  "attempted": false,
  "charge": null,
  "closed": false,
  "currency": "usd",
  "customer": "cus_9UTpVQq30U9bWb",
  "date": 1485271404,
  "description": null,
  "discount": {
    "object": "discount",
    "coupon": {
      "id": "twopets",
      "object": "coupon",
      "amount_off": null,
      "created": 1480277071,
      "currency": null,
      "duration": "forever",
      "duration_in_months": null,
      "livemode": false,
      "max_redemptions": null,
      "metadata": {},
      "percent_off": 5,
      "redeem_by": null,
      "times_redeemed": 7,
      "valid": true
    },
    "customer": "cus_9UTpVQq30U9bWb",
    "end": null,
    "start": 1482593004,
    "subscription": "sub_9nt9bLaaimRN2I"
  },
  "ending_balance": null,
  "forgiven": false,
  "lines": {
    "object": "list",
    "data": [
      {
        "id": "sub_9nt9bLaaimRN2I",
        "object": "line_item",
        "amount": 1998,
        "currency": "usd",
        "description": null,
        "discountable": true,
        "livemode": false,
        "metadata": {},
        "period": {
          "start": 1485271404,
          "end": 1487949804
        },
        "plan": {
          "id": "Product",
          "object": "plan",
          "amount": 999,
          "created": 1470841667,
          "currency": "usd",
          "interval": "month",
          "interval_count": 1,
          "livemode": false,
          "metadata": {},
          "name": "Product",
          "statement_descriptor": "My Pet Defense",
          "trial_period_days": null
        },
        "proration": false,
        "quantity": 2,
        "subscription": null,
        "type": "subscription"
      }
    ],
    "has_more": false,
    "total_count": 1,
    "url": "/v1/invoices/upcoming/lines?customer=cus_9UTpVQq30U9bWb"
  },
  "livemode": false,
  "metadata": {},
  "next_payment_attempt": 1485275004,
  "paid": false,
  "period_end": 1485271404,
  "period_start": 1482593004,
  "receipt_number": null,
  "starting_balance": 0,
  "statement_descriptor": null,
  "subscription": "sub_9nt9bLaaimRN2I",
  "subtotal": 1998,
  "tax": null,
  "tax_percent": null,
  "total": 1898,
  "webhooks_delivered_at": null
}

Here is the output of curl to `https://api.stripe.com/v1/invoices/in_19UHMm2r9wsOBpY0mBeYMi20`
>{
  "id": "in_19UHMm2r9wsOBpY0mBeYMi20",
  "object": "invoice",
  "amount_due": 1898,
  "application_fee": null,
  "attempt_count": 1,
  "attempted": true,
  "charge": "ch_19UHMm2r9wsOBpY0SlLoMkFG",
  "closed": true,
  "currency": "usd",
  "customer": "cus_9UTpVQq30U9bWb",
  "date": 1482593004,
  "description": null,
  "discount": {
    "object": "discount",
    "coupon": {
      "id": "twopets",
      "object": "coupon",
      "amount_off": null,
      "created": 1480277071,
      "currency": null,
      "duration": "forever",
      "duration_in_months": null,
      "livemode": false,
      "max_redemptions": null,
      "metadata": {},
      "percent_off": 5,
      "redeem_by": null,
      "times_redeemed": 7,
      "valid": true
    },
    "customer": "cus_9UTpVQq30U9bWb",
    "end": null,
    "start": 1482593004,
    "subscription": "sub_9nt9bLaaimRN2I"
  },
  "ending_balance": 0,
  "forgiven": false,
  "lines": {
    "object": "list",
    "data": [
      {
        "id": "sub_9nt9bLaaimRN2I",
        "object": "line_item",
        "amount": 1998,
        "currency": "usd",
        "description": null,
        "discountable": true,
        "livemode": false,
        "metadata": {},
        "period": {
          "start": 1482593004,
          "end": 1485271404
        },
        "plan": {
          "id": "Product",
          "object": "plan",
          "amount": 999,
          "created": 1470841667,
          "currency": "usd",
          "interval": "month",
          "interval_count": 1,
          "livemode": false,
          "metadata": {},
          "name": "Product",
          "statement_descriptor": "My Pet Defense",
          "trial_period_days": null
        },
        "proration": false,
        "quantity": 2,
        "subscription": null,
        "type": "subscription"
      }
    ],
    "has_more": false,
    "total_count": 1,
    "url": "/v1/invoices/in_19UHMm2r9wsOBpY0mBeYMi20/lines"
  },
  "livemode": false,
  "metadata": {},
  "next_payment_attempt": null,
  "paid": true,
  "period_end": 1482593004,
  "period_start": 1482593004,
  "receipt_number": null,
  "starting_balance": 0,
  "statement_descriptor": null,
  "subscription": "sub_9nt9bLaaimRN2I",
  "subtotal": 1998,
  "tax": null,
  "tax_percent": null,
  "total": 1898,
  "webhooks_delivered_at": 1482593004
}

**Comment by farmdawgnation** [comment]
Ack. Okay, I'll incorporate this into the test and see that it gets fixed.

**Comment by riveramj** [comment]
added to spec and said it should not equal none. got 

>[info] - should retrieve correct fields from Stripe's JSON *** FAILED ***
[info]   None equaled None (InvoiceSpec.scala:176)

**Comment by riveramj** [comment]
interestingly enough `InvoiceSpec` failed with `None` as well even though I swear it worked in my code o.O

granted these are just hacks to test the theory so could have messed it up.

**Comment by farmdawgnation** [comment]
Let me add you as a collaborator so you can push the spec. Sounds like you're making enough use of streifen to make it worth adding you anyway. :)

**Comment by riveramj** [comment]
ok

**Comment by riveramj** [comment]
pushed w/failing specs

**Comment by riveramj** [comment]
the null in `end` is breaking it. will push fix

**Comment by farmdawgnation** [comment]
Okay, LGTM.

**Pull request merged**
